/*
 * generated by Xtext
 */
package xtraitj.ui;

import org.eclipse.jface.viewers.ILabelProvider;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ui.wizard.IProjectCreator;

import xtraitj.ui.labeling.XtraitjLabelProvider;
import xtraitj.ui.wizard.XtraitjProjectCreatorCustom;

/**
 * Use this class to register components to be used within the IDE.
 */
public class XtraitjUiModule extends xtraitj.ui.AbstractXtraitjUiModule {
	public XtraitjUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	
	@Override
	public Class<? extends IProjectCreator> bindIProjectCreator() {
		return XtraitjProjectCreatorCustom.class;
	}
	
	@Override
	public Class<? extends ILabelProvider> bindILabelProvider() {
		return XtraitjLabelProvider.class;
	}
}
