/*
* generated by Xtext
*/
package xtraitj.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import xtraitj.services.XtraitjGrammarAccess;

public class XtraitjParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private XtraitjGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected xtraitj.parser.antlr.internal.InternalXtraitjParser createParser(XtextTokenStream stream) {
		return new xtraitj.parser.antlr.internal.InternalXtraitjParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "TJProgram";
	}
	
	public XtraitjGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(XtraitjGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
