/**
 * generated by Xtext
 */
package xtraitj.ui.contentassist;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.common.types.TypesPackage.Literals;
import org.eclipse.xtext.ui.editor.contentassist.ContentAssistContext;
import org.eclipse.xtext.ui.editor.contentassist.ICompletionProposalAcceptor;
import xtraitj.ui.contentassist.AbstractXtraitjProposalProvider;
import xtraitj.ui.contentassist.IsInterface;
import xtraitj.xtraitj.TJClass;

/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class XtraitjProposalProvider extends AbstractXtraitjProposalProvider {
  public void completeJvmParameterizedTypeReference_Type(final EObject model, final Assignment assignment, final ContentAssistContext context, final ICompletionProposalAcceptor acceptor) {
    boolean _matched = false;
    if (!_matched) {
      if (model instanceof TJClass) {
        final TJClass _tJClass = (TJClass)model;
        _matched=true;
        IsInterface _isInterface = new IsInterface();
        this.completeJavaTypes(context, 
          Literals.JVM_PARAMETERIZED_TYPE_REFERENCE__TYPE, _isInterface, acceptor);
      }
    }
    if (!_matched) {
      super.completeJvmParameterizedTypeReference_Type(model, assignment, context, acceptor);
    }
  }
}
