language: java

matrix:
  fast_finish: true
  include:
    - os: linux
      jdk: oraclejdk8
    - os: osx
      osx_image: xcode8

cache:
  directories:
  - $HOME/.m2

env: DISPLAY=:99.0

addons:
  apt:
    packages:
    - metacity

install: true

#before_install:
# - sudo apt-get update
# - sudo apt-get install gnome-themes-standard
# - sudo apt-get install metacity
# - sudo apt-get install libwebkit-dev

before_install:
 - bash -e ./before_script.sh

# Temporarily disable coveralls
#  -Pjacoco-report coveralls:report
 
script:
 - export
 - mvn -f xtraitj.releng/pom.xml clean verify -U -Dfindbugs.skip=true
