/*
 * generated by Xtext
 */
package xtraitj.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import xtraitj.ui.internal.XtraitjActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class XtraitjExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return XtraitjActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return XtraitjActivator.getInstance().getInjector(XtraitjActivator.XTRAITJ_XTRAITJ);
	}
	
}
