/**
 * generated by Xtext
 */
package xtraitj.ui.labeling;

import org.eclipse.xtext.ui.label.DefaultDescriptionLabelProvider;

/**
 * Provides labels for a IEObjectDescriptions and IResourceDescriptions.
 * 
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#labelProvider
 */
@SuppressWarnings("all")
public class XtraitjDescriptionLabelProvider extends DefaultDescriptionLabelProvider {
}
