/*
 * generated by Xtext 2.10.0
 */
package xtraitj.ui.wizard;

import org.eclipse.ui.dialogs.WizardNewProjectCreationPage;

public class XtraitjWizardNewProjectCreationPage extends WizardNewProjectCreationPage {

	public XtraitjWizardNewProjectCreationPage(String pageName) {
		super(pageName);
	}

}
