/*
 * generated by Xtext 2.10.0
 */
package xtraitj.tests

import com.google.inject.Inject
import org.eclipse.xtext.junit4.InjectWith
import org.eclipse.xtext.junit4.XtextRunner
import org.eclipse.xtext.junit4.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith
import xtraitj.xtraitj.TJProgram

@RunWith(XtextRunner)
@InjectWith(XtraitjInjectorProvider)
class XtraitjParsingTest{

	@Inject
	ParseHelper<TJProgram> parseHelper

	@Test 
	def void loadModel() {
		val result = parseHelper.parse('''
			trait T {
				String m();
			}
			
			trait T1 uses T, T[rename m to n] {}
		''')
		Assert.assertNotNull(result)
	}

}
