/*
* generated by Xtext
*/
package xtraitj;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class XtraitjUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return xtraitj.ui.internal.XtraitjActivator.getInstance().getInjector("xtraitj.Xtraitj");
	}
	
}
