/**
 * generated by Xtext
 */
package xtraitj.scoping;

import com.google.common.base.Objects;
import com.google.inject.Inject;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EReference;
import org.eclipse.xtext.scoping.IScope;
import org.eclipse.xtext.xbase.annotations.scoping.XbaseWithAnnotationsScopeProvider;
import org.eclipse.xtext.xbase.lib.Extension;
import xtraitj.scoping.TraitJScopeProviderUtil;

/**
 * This class contains custom scoping description.
 * 
 * see : http://www.eclipse.org/Xtext/documentation/latest/xtext.html#scoping
 * on how and when to use it
 */
@SuppressWarnings("all")
public class TraitJXbaseScopeProvider extends XbaseWithAnnotationsScopeProvider {
  @Inject
  @Extension
  private TraitJScopeProviderUtil _traitJScopeProviderUtil;
  
  public IScope getScope(final EObject context, final EReference reference) {
    IScope _xblockexpression = null;
    {
      final IScope scope = this._traitJScopeProviderUtil.createCustomScope(context, reference);
      boolean _notEquals = (!Objects.equal(scope, null));
      if (_notEquals) {
        return scope;
      }
      IScope _scope = super.getScope(context, reference);
      _xblockexpression = (_scope);
    }
    return _xblockexpression;
  }
}
